#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
npm run lint
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'
echo ":building_construction::builder:${yellow} Executing pre-commit hook...${no_color}:male-builder::building_construction:"
echo ":building_construction::builder: ${green} Styling your project before committing...${no_color}:male-builder::building_construction:"
echo ":building_construction::builder:  ${green} please be patient, this may take a while...${no_color}:male-builder::building_construction:"
exec 1>&2
# enable user input
exec < /dev/tty
consoleregexp='console\.[clear|dir|log|info]'
# CHECK
if test $(git diff --cached | grep $consoleregexp | wc -l) != 0
then
  exec git diff --cached | grep -ne $consoleregexp
  echo  "${red} COMMIT REJECTED!  Found console. references. Please remove them before committing.\n${no_color}"
    exit 1;
fi
# Check ESLint Standards
npx lint-staged ||
(
    echo ":hammer::x: ${red} Yoo, you have a problem in your code. Check linter :hammer::x:
          Run yarn lint, add changes and try commit again.${no_color}";
    false;
)
echo "${green}No console. references found!${no_color}\n"
echo "${green}Git pre-commit hook was successful!${no_color}\n"
echo ":tada: ${green} No error found: Checking the commit message....${no_color} :sparkles::rocket::man-surfing::beers:"